const countries = {
  "ar-SA": "Arabic",
  "de-DE": "German",
  "el-GR": "Greek",
  "en-GB": "English",
  "es-ES": "Spanish",
  "fa-IR": "Persian",
  "bn": "Bengali", 
  "fr-FR": "French",
  "gu-IN": "Gujarati",
  "hi-HI": "Hindi",
  "id-ID": "Indonesian",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "kn-IN": "Kannada",
  "ko-KR": "Korean",
  "ne-NP": "Nepali",
  "ur-PK": "Pakistani",
  "pa-IN": "Panjabi",
  "pt-PT": "Portuguese",
  "ru-RU": "Russian",
  "ta-LK": "Tamil",
  "te-IN": "Telugu"
}